language: haskell
ghc:
  # - '7.10.2'
  - '8.4.3'
  # - '8.2.2'
  - '8.0'
env:
  - PACKAGE=get-zapped

before_install:
  - cabal sandbox init

install:
  - cabal update

script:
  - curl -sSL https://get.haskellstack.org/ | sh
  - stack setup
  - stack update
  - stack init
  - stack build
  - stack test
